const data = {
  products: [
    {
      name: 'X-Men Retro 90s T-Shirt',
      slug: 'X-Men-Animated-Series',
      category: 'T-Shirt',
      image: '/images/T-Shirt1.jfif',
      price: 249,
      brand: 'Marvel',
      rating: 3.0,
      numReviews: 52,
      countInStock: 10,
      description: 'Retro Marvel Shirts for Men, Women, Boys, and Girls',
    },
    {
      name: 'Retro Comic Graphic T-Shirt',
      slug: 'Retro-Comic-Graphic-Shirt',
      category: 'T-Shirt',
      image: '/images/T-Shirt2.jfif',
      price: 249,
      brand: 'Marvel',
      rating: 3.2,
      numReviews: 32,
      countInStock: 9,
      description: 'Officially Licensed Marvel Tee Shirt',
    },
    {
      name: 'Father Super Hero T-Shirt',
      slug: 'Father-SuperHero-Shirt',
      category: 'T-Shirt',
      image: '/images/T-Shirt3.jpg',
      price: 199,
      brand: 'Marvel',
      rating: 3.3,
      numReviews: 8,
      countInStock: 14,
      description: 'Fashion slim fit t-shirt',
    },
    {
      name: 'Dead-Pool T-Shirt',
      slug: 'Dead-Pool-Shirt',
      category: 'T-Shirt',
      image: '/images/T-Shirt4.jpg',
      price: 299,
      brand: 'Marvel',
      rating: 4.5,
      numReviews: 25,
      countInStock: 10,
      description: 'Officially Licensed Marvel Tee Shirt',
    },
    {
      name: 'Groot T-Shirt',
      slug: 'Groot-Shirt',
      category: 'T-Shirt',
      image: '/images/T-Shirt5.jpg',
      price: 299,
      brand: 'Marvel',
      rating: 3.9,
      numReviews: 39,
      countInStock: 8,
      description: 'Officially Licensed Marvel Tee Shirt',
    },
    {
      name: 'Wolverine T-Shirt',
      slug: 'Wolverine-Shirt',
      category: 'T-Shirt',
      image: '/images/T-Shirt6.jpg',
      price: 349,
      brand: 'Marvel',
      rating: 4.3,
      numReviews: 49,
      countInStock: 10,
      description: 'Officially Licensed Marvel Tee Shirt',
    },
    {
      name: 'FunkoVerse Thanos',
      slug: 'Funkoverse-Thanos',
      category: 'Funko',
      image: '/images/Funko2.jpg',
      price: 999,
      brand: 'Pop',
      rating: 4.0,
      numReviews: 26,
      countInStock: 6,
      description:
        'Play with one of the most powerful beings in the Marvel Universe!',
    },
    {
      name: 'FunkoPop Iron Man',
      slug: 'Funkopop-Iron-Man',
      category: 'Funko',
      image: '/images/Funko1.jpg',
      price: 999,
      brand: 'Pop',
      rating: 4.8,
      numReviews: 122,
      countInStock: 9,
      description:
        'Capture the most epic moment from Avengers: Endgame for your collection',
    },
    {
      name: 'FunkoPop Captain Carter',
      slug: 'Funkopop-Captain-Carter',
      category: 'Funko',
      image: '/images/Funko3.jpg',
      price: 399,
      brand: 'Pop',
      rating: 3.5,
      numReviews: 158,
      countInStock: 11,
      description:
        'From What if=,Captain Carter, as a stylized Pop! from funko',
    },
    {
      name: 'FunkoPop Sylvie',
      slug: 'Funkopop-Sylvie',
      category: 'Funko',
      image: '/images/Funko4.jpg',
      price: 489,
      brand: 'Pop',
      rating: 4.0,
      numReviews: 221,
      countInStock: 6,
      description:
        'From Marvels Loki Disney Plus show, Sylvie,as a stylized Pop! from funko.',
    },
    {
      name: 'FunkoPop Dead Strange',
      slug: 'Funkopop-Dead-Strange',
      category: 'Funko',
      image: '/images/Funko5.jpg',
      price: 449,
      brand: 'Pop',
      rating: 4.5,
      numReviews: 49,
      countInStock: 10,
      description: 'From What if=,Dead Strange, as a stylized Pop! from funko',
    },
    {
      name: 'FunkoPop Infinity Ultron',
      slug: 'Funkopop-Infinity-Ultron',
      category: 'Funko',
      image: '/images/Funko6.jpg',
      price: 399,
      brand: 'Pop',
      rating: 5.0,
      numReviews: 33,
      countInStock: 4,
      description:
        'Play with one of the most powerful beings in the Marvel Universe!',
    },
    {
      name: 'Thor Mjolnir',
      slug: 'Thor-Mjolnir',
      category: 'Collectibles',
      image: '/images/colec1.jpg',
      price: 3399,
      brand: 'Marvel Legends',
      rating: 4.6,
      numReviews: 29,
      countInStock: 8,
      description:
        'Mjolnir Premium Electronic Role Play Hammer inspired by marvel thor: love and thunder.',
    },
    {
      name: 'Captain America Shield',
      slug: 'Captain-America-Shield',
      category: 'Collectibles',
      image: '/images/colec2.jpg',
      price: 4339,
      brand: 'Marvel Legends',
      rating: 4.7,
      numReviews: 107,
      countInStock: 5,
      description:
        'HIGH QUALITY SHIELD WITH ADJUSTABLE STRAPS: This premium collector shield features adjustable straps to allow wearing the shield like Captain America does when entering the fight for justice.',
    },
    {
      name: 'Eye Of Agamotto',
      slug: 'Eye-Of-Agamotto',
      category: 'Collectibles',
      image: '/images/colec3.jpg',
      price: 1200,
      brand: 'Marvel Legends',
      rating: 4.5,
      numReviews: 35,
      countInStock: 9,
      description:
        'Luminous Eye Of Amamotto is a premium talisman inspired by Doctor Strange Mystical object in the MCU.',
    },
    {
      name: 'Tesseract',
      slug: 'Tesseract-Loki',
      category: 'Collectibles',
      image: '/images/colec4.jpg',
      price: 1849,
      brand: 'Marvel Legends',
      rating: 4.5,
      numReviews: 40,
      countInStock: 5,
      description: 'Premium Electronic Tesseract For Role Playing.',
    },
    {
      name: 'Iron Spider',
      slug: 'Iron-Spider',
      category: 'Collectibles',
      image: '/images/colec5.jpg',
      price: 2700,
      brand: 'Marvel Legends',
      rating: 4.0,
      numReviews: 32,
      countInStock: 5,
      description:
        'Premium role-playing helmet with light effects inspired by Iron Spider technology designed by Tony Stark',
    },
    {
      name: 'Iron Man Electronic Helmet',
      slug: 'IronMan-Electronic-Helmet',
      category: 'Collectibles',
      image: '/images/colec6.jpg',
      price: 3150,
      brand: 'Marvel Legends',
      rating: 4.9,
      numReviews: 99,
      countInStock: 12,
      description:
        'Premium role-playing helmet with light effects inspired by Iron Man technology designed by Tony Stark',
    },
    {
      name: 'Iron Man Nano Gauntlet',
      slug: 'IronMan-NanoGauntlet',
      category: 'Collectibles',
      image: '/images/colec7.jpg',
      price: 3200,
      brand: 'Marvel Legends',
      rating: 4.5,
      numReviews: 99,
      countInStock: 15,
      description: 'Premium Marvel Legends RPG Item',
    },
    {
      name: 'Infinity Gauntlet',
      slug: 'Infinity-Guantlet',
      category: 'Collectibles',
      image: '/images/colec8.jpg',
      price: 3880,
      brand: 'Marvel Legends',
      rating: 4.6,
      numReviews: 129,
      countInStock: 10,
      description: 'Premium Marvel Legends RPG Item',
    },
    {
      name: 'Age Of Ultron #1 (2013).',
      slug: 'Age-Of-Ultron-2013',
      category: 'Comics',
      image: '/images/Comic1.jpg',
      price: 1494,
      brand: 'Marvel Comics',
      rating: 4.5,
      numReviews: 378,
      countInStock: 8,
      description:
        'For years the heroes of the Marvel Universe have lived in fear that the artificial intelligence known as Ultron would one day evolve to fulfill its desire to wipe out all organic life and take over the Earth - that day has arrived. ',
    },
    {
      name: 'Avengers #1 (2018).',
      slug: 'Avengers-2018',
      category: 'Comics',
      image: '/images/Comic2.jpg',
      price: 1200,
      brand: 'Marvel Comics',
      rating: 4.5,
      numReviews: 116,
      countInStock: 7,
      description:
        'Thor Odinson. Steve Rogers. Tony Stark. The Big Three of the Avengers are reunited at last! And just in time to save the world from total annihilation at the hands of their most powerful enemies yet:',
    },
    {
      name: 'Infinity Gauntlet (1991)',
      slug: 'Infinity-Gauntlet-1991',
      category: 'Comics',
      image: '/images/Comic3.jpg',
      price: 1200,
      brand: 'Marvel Comics',
      rating: 4.5,
      numReviews: 116,
      countInStock: 7,
      description:
        'One of the biggest events ever to hit the Marvel Universe! For Thanos, the Infinity Gauntlet was the ultimate prize to be coveted above all else.',
    },
    {
      name: 'Vision (2015)',
      slug: 'Vision-2015',
      category: 'Comics',
      image: '/images/Comic4.jpg',
      price: 500,
      brand: 'Marvel Comics',
      rating: 4.0,
      numReviews: 99,
      countInStock: 20,
      description:
        'The Vision wants to be human, and whats more human than family? He goes to the laboratory where he was created, where Ultron molded him into a weapon, where he first rebelled against his given destiny, where he first imagined that he could be more, that he could be good, that he could be a man, a normal, ordinary man. And he builds them. A wife, Virginia. Two teenage twins, Viv and Vin.',
    },
  ],
};
export default data;
