const data = {
  products: [
    {
      name: 'X-Men Animated Series Retro 90s T-Shirt',
      slug: 'X-Men-Animated-Series',
      category: 'T-Shirt',
      image: '/images/T-Shirt1.jfif',
      price: 464,
      brand: 'Marvel',
      rating: 4.7,
      numReviews: 52,
      countInStock: 20,
      description: 'Retro Marvel Shirts for Men, Women, Boys, and Girls',
    },
    {
      name: 'Retro Comic Graphic T-Shirt',
      slug: 'Retro-Comic-Graphic-Shirt',
      category: 'T-Shirt',
      image: '/images/T-Shirt2.jfif',
      price: 464,
      brand: 'Marvel',
      rating: 4.8,
      numReviews: 26,
      countInStock: 6,
      description: 'Officially Licensed Marvel Tee Shirt',
    },
    {
      name: 'FunkoVerse Thanos',
      slug: 'Funkoverse-Thanos',
      category: 'Funko',
      image: '/images/funko2.png',
      price: 464,
      brand: 'Pop',
      rating: 4.8,
      numReviews: 26,
      countInStock: 6,
      description:
        'Play with one of the most powerful beings in the Marvel Universe!',
    },
    {
      name: 'FunkoPop Iron Man',
      slug: 'Funkopop-Iron-Man',
      category: 'Funko',
      image: '/images/Funko1.jpg',
      price: 566,
      brand: 'Pop',
      rating: 4.8,
      numReviews: 122,
      countInStock: 9,
      description:
        'Capture the most epic moment from Avengers: Endgame for your collection',
    },
    {
      name: 'Thor Mjolnir',
      slug: 'Thor-Mjolnir',
      category: 'Collectibles',
      image: '/images/colec1.jpg',
      price: 3231,
      brand: 'Marvel Legends',
      rating: 4.6,
      numReviews: 29,
      countInStock: 15,
      description:
        'PREMIUM ROLEPLAY ELECTRONIC HAMMER: This Marvel Legends Premium roleplay hammer is 1:1 full scale, inspired by the iconic Marvel item’s',
    },
    {
      name: 'Captain America Shield',
      slug: 'Captain-America-Shield',
      category: 'Collectibles',
      image: '/images/colec2.jpg',
      price: 4339,
      brand: 'Marvel Legends',
      rating: 4.7,
      numReviews: 64,
      countInStock: 10,
      description:
        'HIGH QUALITY SHIELD WITH ADJUSTABLE STRAPS: This premium collector shield features adjustable straps to allow wearing the shield like Captain America does when entering the fight for justice.',
    },
  ],
};
export default data;
